/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import React from 'react';
import { ArrowPathIcon, ArrowRightIcon } from './icons';

interface VideoResultProps {
  videoUrl: string;
  onRetry: () => void;
  onNewVideo: () => void;
  onExtend: () => void;
  canExtend: boolean;
}

const VideoResult: React.FC<VideoResultProps> = ({
  videoUrl,
  onNewVideo,
}) => {
  return (
    <div className="w-full flex flex-col">
      <div className="relative w-full aspect-video bg-black">
        <video
          src={videoUrl}
          controls
          autoPlay
          className="w-full h-full object-contain"
        />
      </div>
      <div className="p-6 flex flex-col sm:flex-row items-center justify-between gap-4 bg-[#1f1f1f]">
        <div className="text-sm text-gray-400">
          Generated by Veo 3.1
        </div>
        <button
          onClick={onNewVideo}
          className="flex items-center gap-2 px-6 py-2.5 bg-gray-700 hover:bg-gray-600 text-white font-medium rounded-lg transition-all hover:scale-105">
          <ArrowPathIcon className="w-4 h-4" />
          New Forecast
        </button>
      </div>
    </div>
  );
};

export default VideoResult;
